import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";

const outfit = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin", "cyrillic"],
  weight: ['400']
});

export const metadata: Metadata = {
  title: "Vera",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <body

        className={`${outfit.variable}`}
      >
        {children}
        
      </body>
      <Head>
        <link rel="icon" href="/vera-logo-rounded.png" />
      </Head>
      <Footer />
    </html>
  );
}